### PR TITLE
Say something

### PR DESCRIPTION
**Pull request by cclauss**
An oversight in my last PR...

### CODE REVIEW

**Comment by mertyildiran** [comment]
@cclauss I don't understand the purpose of this PR. Please give me more information. :blush:

**Comment by cclauss** [comment]
I made a mistake on the last PR that we merged so now Dragonfire does not say anything when these commands are executed.

**Comment by mertyildiran** [comment]
@cclauss could you point out the mistake? (with a link or a few lines of code)

**Comment by cclauss** [comment]
Just look at the diff...  Currently it reads __userin.say()__ which says nothing at all.  I am trying to get dragonfire to say __say_test__ instead of nothing at all.

**Pull request merged**
