### PR TITLE
Fix some styling issues, bugs and increase performance during reminder loops

### PR DESCRIPTION
**Pull request by MCYBA**

### CODE REVIEW

**Comment by MCYBA** [comment]
@mertyildiran hello mister, I created test files for take_note.py submodule and takenote.py submodule of dragonfire taking note ability with if-else structure.

**Comment by mertyildiran** [comment]
@MCYBA please do the following changes:

 - Rename `dragonfire.commands.takenote_submodules` module to `dragonfire.commands.takenote`.
 - Do not use numbers in module names. Try to combine these two files: `check_take_compare1.py` and `check_take_compare2.py` into a single file.
 - There is an inconsistency on the naming of `take_note` and `takenote` choose one of them and stick with it.
 - I'm still unsure about the functionality of the note taking feature. I will look further into it. The unit tests that you have wrote are not so meaningful. Why did you add two different test files for the same functionality? Please try to combine `test_dragonfire_takenote.py` and `test_take_note.py` into a single file. There is already `test_dragonfire.py` for testing Dragonfire as a whole. If your purpose is testing the imports of the note taking feature into the top level module then write those tests into `test_dragonfire.py` do not create another file.

**Comment by MCYBA** [comment]
I divided code blocks into these files( `check_take_compare1.py` and `check_take_compare2.py`) for managing the code better. İf you want to see these files into a single one, I will, or maybe I can rename both?
For this file `test_dragonfire_takenote.py`, İf I put codes into the `test_dragonfire.py`, file was become waste. Please, verify for the last time, should I do this?

**Comment by mertyildiran** [comment]
@MCYBA please combine these two files: `check_take_compare1.py` and `check_take_compare2.py` into a single file. Shorter file does not mean more manageable/maintainable. A long but well written file can also be easily maintained. You should create a new module only if it serves a completely different purpose and that's not your case right now. Functions of (actually) the same class on multiple files is unacceptable.

**Comment by MCYBA** [comment]
After what you say, I wrote new classes for fixing the styling issue. What do you think about this correction?

**Comment by mertyildiran** [comment]
@MCYBA oops this time Travis CI build failed. Again this is not what I'm asking. There should be one file, one or maybe two classes and the functions go under that class. There is no such thing as "*Add new classes instead functions*". Also please don't use numbers anywhere like in module, class or function names.

Travis CI failure might now related to this PR and just a failed to download issue. I'm restarting the build...

**Comment by mertyildiran** [comment]
By the way don't forget to **squash** your last commits since no one wants to see unnecessary amount of commits. You should also squash unnecessary commits into a single one like https://github.com/DragonComputer/Dragonfire/pull/103/commits/1922f9f48bde2512d07f04425f9c6bdc659b912a and https://github.com/DragonComputer/Dragonfire/pull/103/commits/666a8b64341c3107eb1ee3c527149d0098914ac8 .

Also use **imperative mood** and **capitalize** your commit messages. `Correction` as a commit message is unacceptable and also it's not descriptive enough. `correction takenote.py check submodules explanation lines` is also not an imperative sentence. Fix your grammar and punctuation.

Last but not least, **do not** use dot [.] at the end of the first lines of the commit messages. Since the first line of a commit message is actually **serves as the title** of the commit.

**Comment by MCYBA** [comment]
@mertyildiran Mister, I am confused little bit about git jobs but I think mission completed. :)
There is just one file I did not change like your wants: `test_dragonfire_takenote.py`. Should I merge it with `test_dragonfire.py`?

**Comment by mertyildiran** [comment]
@MCYBA you should rename `test_dragonfire_takenote.py` as `test_takenote.py` and fix the commit message 

`::white_check_mark: add test file for testing dragonfire taking note ability.`  to 

`:white_check_mark: Add tests for Dragonfire's note taking ability`

**Comment by MCYBA** [comment]
All requirements passed mister?

**Pull request merged**
