### PR TITLE
Integrate the programs shutdown feature.

### PR DESCRIPTION
**Pull request by MCYBA**
Integrate the "shutdown of programs" and "install the not installed programs during opening the programs" features.

### CODE REVIEW

**Comment by mertyildiran** [comment]
```plain
Enter your command: hey
You: HEY
Dragonfire: WHAT IS YOUR ORDER?
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: Open calculator
You: OPEN CALCULATOR
Dragonfire: CALCULATOR NOT FOUND! DO YOU WANT TO INSTALL?
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: Yes
You: YES
Dragonfire: I WON'T INSTALL!
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: open files
You: OPEN FILES
Dragonfire: FILE MANAGER
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: close files
You: CLOSE FILES
Dragonfire: FILE MANAGER CLOSED
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: open camera
You: OPEN CAMERA
Dragonfire: CAMERA NOT FOUND! DO YOU WANT TO INSTALL?
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: yes
You: YES
Dragonfire: CHOOSE ONE OF FOLLOWING:
KAMOSO
SNAP-PHOTOBOOTH
CHEESE

______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: 1
You: 1
Dragonfire: PLEASE REPEAT!
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: Dragonfire: WELL, MAYBE ...
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


Enter your command: KAMOSO
You: KAMOSO
Dragonfire: PLEASE REPEAT!
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: Dragonfire: THE MONKEY! HE'S A WHEEL!
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


Enter your command: open camera
You: OPEN CAMERA
Dragonfire: PLEASE REPEAT!
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: Dragonfire: CAMERA NOT FOUND! DO YOU WANT TO INSTALL?
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

yes
You: YES
Dragonfire: CHOOSE ONE OF FOLLOWING:
KAMOSO
SNAP-PHOTOBOOTH
CHEESE

______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: KAMOSO
You: KAMOSO
Dragonfire: PLEASE REPEAT!
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: Dragonfire: THE MONKEY! HE'S A WHEEL!
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
```

Above is the conversation dump of my tests for this PR.

Seems like something is broken. I sat "*Open calculator*" and give answer "*Yes*" but she says: "*I WON'T INSTALL!*".

When I say "*Open camera*" and "*Yes*" she says:

```plain
Dragonfire: CHOOSE ONE OF FOLLOWING:
KAMOSO
SNAP-PHOTOBOOTH
CHEESE
```

and even though I answer as "*1*" or "*KAMOSO*" she says "*PLEASE REPEAT!*". First of all it should not even happen. Why is she asking for me to choose an application? She should try to install all of the alternatives automatically. Only one or two will be available in the package repository of the distro. For sure this feature is completely broken, please fix it and update your PR.

By changing it to `return userin.say(userin.execute(cmds, "LibreOffice Writer", user_answering))` or `return userin.say(userin.execute(cmds, "Web Browser", False, 0, is_kill))` you made it overly complex. Sometimes you are passing `is_kill` parameter and sometimes not, that's not OK. Also if it's a **keyword argument** pass it like `is_kill=is_kill` for the sake of readability.

`cmds = [["konsole", "--command=sudo apt install " + com], ["gnome-terminal", "--command=sudo apt install " + com]]` is not the way of doing this. There are cases that binary executable name in the `PATH` does not match to the package name. You should specifically define the package name for the each program that Dragonfire supports. Also use `apt-get install` instead of `apt install` for backward compatibility. Before Ubuntu 16.04 there was no such thing as `apt`.

**Comment by mertyildiran** [comment]
The conversation should go like this:

```plain
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

You: OPEN CALCULATOR
Dragonfire: SEEMS LIKE CALCULATOR IS NOT INSTALLED ON YOUR SYSTEM. DO YOU WANT ME TO INSTALL IT?
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

You: YES
Dragonfire: INSTALLING CALCULATOR...
Dragonfire: CALCULATOR HAS BEEN INSTALLED
Dragonfire: OPENING CALCULATOR
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

You: CLOSE THE CALCULATOR
Dragonfire: CALCULATOR HAS BEEN CLOSED
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
```

**Comment by mertyildiran** [comment]
Here is the conversation dump of the current state of your PR:

```plain
Enter your command: hey
You: HEY
Dragonfire: SIR, TELL ME YOUR WISH.
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: Open calculator
You: OPEN CALCULATOR
Dragonfire: SEEMS LIKE CALCULATOR IS NOT INSTALLED ON YOUR SYSTEM. DO YOU WANT ME TO INSTALL IT?
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: Yes
You: YES
Dragonfire: OKAY, I WON'T INSTALL!
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: file manager
You: FILE MANAGER
Dragonfire: OUCH!
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: Open files
You: OPEN FILES
Dragonfire: FILE MANAGER
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
```

and

```plain
Enter your command: Open calculator
You: OPEN CALCULATOR
Dragonfire: SEEMS LIKE CALCULATOR IS NOT INSTALLED ON YOUR SYSTEM. DO YOU WANT ME TO INSTALL IT?
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: yes
You: YES
Dragonfire: INSTALLING WILL START, PLEASE ENTER YOUR ROOT PASSWORD.
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: Dragonfire: INSTALLING WILL START, PLEASE ENTER YOUR ROOT PASSWORD.
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


Enter your command: Open calculator
You: OPEN CALCULATOR
Dragonfire: SEEMS LIKE CALCULATOR IS NOT INSTALLED ON YOUR SYSTEM. DO YOU WANT ME TO INSTALL IT?
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
```

seems like still something is broken. She should have start to install calculator after I say "*Yes*" and with lower case input "*yes*" she said "*INSTALLING WILL START, PLEASE ENTER YOUR ROOT PASSWORD.*" but nothing happened.

On the other hand, I moved some of the commands like "*File manager*", "*Software center*", "*Office suite*" to outside of the block that checks for verbs like "*Open, Run, Start*" for fixing the commands to match with the examples given in README.md. But you have reverted back my changes so it's not OK.

Why are you passing a dictionary if the shell command is exactly the same in each distro?:

```python
cmds = [{'distro': 'KDE neon', 'name': ["sensible-browser", wikipage.url]}, {'distro': 'Linux Mint', 'name': ["sensible-browser", wikipage.url]}, {'distro': 'Ubuntu', 'name': ["sensible-browser", wikipage.url]}, {'distro': 'elementary OS', 'name': ["sensible-browser", wikipage.url]}]
cmds = [{'distro': 'KDE neon', 'name': ["echo"]}, {'distro': 'Linux Mint', 'name': ["echo"]}, {'distro': 'Ubuntu', 'name': ["echo"]}, {'distro': 'elementary OS', 'name': ["echo"]}]
cmds = [{'distro': 'KDE neon', 'name': [" "]}, {'distro': 'Linux Mint', 'name': [" "]}, {'distro': 'Ubuntu', 'name': [" "]}, {'distro': 'elementary OS', 'name': [" "]}]
```

You did not met the condition that I stated on my previous comment:
> By changing it to `return userin.say(userin.execute(cmds, "LibreOffice Writer", user_answering))` or `return userin.say(userin.execute(cmds, "Web Browser", False, 0, is_kill))` you made it overly complex. Sometimes you are passing `is_kill` parameter and sometimes not, that's not OK. Also if it's a **keyword argument** pass it like `is_kill=is_kill` for the sake of readability.

**Comment by mertyildiran** [comment]
Still installation feature does not work:

```plain

Enter your command: Open calculator
You: OPEN CALCULATOR
Dragonfire: SEEMS LIKE CALCULATOR IS NOT INSTALLED ON YOUR SYSTEM. DO YOU WANT ME TO INSTALL IT?
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: Yes
You: YES
Dragonfire: INSTALLING CALCULATOR...
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: Open calculator
You: OPEN CALCULATOR
Dragonfire: SEEMS LIKE CALCULATOR IS NOT INSTALLED ON YOUR SYSTEM. DO YOU WANT ME TO INSTALL IT?
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: Open files
You: OPEN FILES
Dragonfire: OKAY, I WON'T INSTALL!
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
```

Also you messed up some built-in commands that are not starting with *Open* verb:

```plain
Enter your command: Open files
You: OPEN FILES
Dragonfire: FILE MANAGER
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: Close files
You: CLOSE FILES
Dragonfire: FILE MANAGER HAS BEEN CLOSED
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: Close browser
You: CLOSE BROWSER
Dragonfire: WEB BROWSER IS NOT OPEN!
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: photo editor
You: PHOTO EDITOR
Dragonfire: TWENTY-SIX MINUTES.
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: photoshop
You: PHOTOSHOP
Dragonfire: THE MONKEY! HE'S A WHEEL!
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: gimp
You: GIMP
Dragonfire: WE'RE IN THE SUB. UNHARMED.
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: open gimp
You: OPEN GIMP
Dragonfire: THE PHOTO EDITOR SOFTWARE
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

Enter your command: close gimp
You: CLOSE GIMP
Dragonfire: THE PHOTO EDITOR SOFTWARE HAS BEEN CLOSED
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
```

[This change](https://github.com/DragonComputer/Dragonfire/pull/107/files#diff-bfed9051c289971a1b77ef0deacd2d18) is wrong.

It does not seem correct to use string operations approach in here:

```python
if "install**" in msg:
    msg = msg.replace("install**", "")
    program_name = name[1].replace("apt-get install ", "")
```

Installation cannot be canceled but can fail:

```python
self.say("Installation Cancelled!")
```

Is exist what? `if is_exist:` Bad variable name choice.

You should investigate the possible solutions in `python-apt` package.

Closing the programs seems partially work. I tried to close the browser and it does not work.

Still I don't understand why do you push to different feature additions in a single PR.

If you are defining a long array or a long dictionary use multiple lines. Not like this:

```python
cmds = [{'distro': 'KDE neon', 'name': ['korganizer']}, {'distro': 'elementary OS', 'name': ['maya-calendar']}, {'distro': 'Ubuntu', 'name': ['orage']}, {'distro': 'Linux Mint', 'name': ['gnome-calendar']}]
```

`gksudo` is not avaiable in KDE environment. For KDE there is `kdesu` but it's not in PATH so you should symlink with `sudo ln -s /usr/lib/x86_64-linux-gnu/libexec/kf5/kdesu /usr/bin/kdesu`. `python-apt` might have a better solution than using `gksudo` or `kdesu`.

**Comment by MCYBA** [comment]
Into this file: https://github.com/DragonComputer/Dragonfire/pull/107/files#diff-b101058c230a3453693341927e0b4472 :
  `cmd(str)` object replace with the  `cmds(dictionary)` object. And under the` try/except`(starting from line 91) block `userin.execute()` function is checking the program that is user wants to open is exist, and according the answer, opening program or installing it.

  `else` block it is starting from line 140,  is for closing the programs that are user wants.

into this file: https://github.com/DragonComputer/Dragonfire/pull/107/files#diff-bfed9051c289971a1b77ef0deacd2d18 
   Realized changes are for to use `userin.execute()` function return value.

into this: https://github.com/DragonComputer/Dragonfire/pull/107/files#diff-b037cff70e110194387688ac9a8148ad and this files: https://github.com/DragonComputer/Dragonfire/pull/107/files#diff-06a0a7f80f5a8171b61442b361642c99
   Realized changes are for to use the first parameter `userin.execute()` function that is changed into the `utilities.py`, as dictionary object.

and the other files for the adding requirements that is `psutil` into the `setup.py`,` install.sh` and the other necessary places.

**Comment by MCYBA** [comment]
Mister, I did not find the cause of the failure. It looks because of the result of `omniscient.py`. Have you any idea about that?

**Pull request closed without merging**
