### PR TITLE
Simplify by defining a common usage pattern: TTA.define_and_execute()

### PR DESCRIPTION
**Pull request by cclauss**
['VirtualAssistant.command' is too complex (72)](https://travis-ci.org/DragonComputer/Dragonfire/jobs/293886399#L579).  72 is the measurement of the method's [McCabe complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity).  I have rarely seen numbers in 20's but I have never a number so high.  This PR's changes do not lower that number but some work should go into refactoring this method to make it more understandable for the first time reader.  ;-)

Also:
* Sort imports with isort (optional but does make imports easier to comprehend)
* Use isinstance() when comparing types
* Use random.choice() on a tuple instead of random.randint() on a dict
* Remove repetition from time_of_day logic.

### CODE REVIEW

**Comment by mertyildiran** [comment]
@cclauss firstly, conversion from `TTA.define()` and `TTA.execute()` to `TTA.define_and_execute()` is incomplete, such as [this line](https://github.com/DragonComputer/Dragonfire/blob/master/dragonfire/omniscient.py#L59).

Combining `TTA.define()` and `TTA.execute()` into a single function will reduce the flexibility for developers who want to write more complex blocks. (i.e. execute the same command over and over again under a loop with unknown iteration count) So these kind of functions need to be as atomic as possible.

Replacing `print("_______________________________________________________________\n")` with `print("_" * 63 + "\n")` will make it hard to find with a text search in the repository. When I write a comment lines like `#print "TTS process started."` (without spacing after `#`), it indicates a commented code line, not an actual comment. My way contradicts with Flake8's default though.

I saw ['VirtualAssistant.command' is too complex (72)](https://travis-ci.org/DragonComputer/Dragonfire/jobs/293886399#L579) warning too. But `VirtualAssistant.command()` is an unusual function. Do you have a better idea than using a long chain of `if-elif-else`? We can choose to encapsulate the each block under an `if/elif` statement with defining a function but why would we do that? What is the benefit of doing that? Performance?

**Comment by cclauss** [comment]
I do not advocate doing away with `TTA.define()` and `TTA.execute()`.  This PR says that the combination is a common pattern, not a universal pattern.  The two functions have their place as separate functions and there were several instances where I did not attempt to merge them because I understood that they were not directly combined.  I also did not try to find all the places in all files where they could be combined but was focused on shortening the special `VirtualAssistant.command()` method.

I think we can use dict lookup to simplify VirtualAssistant.command() and also process ("SEARCH" in com or "FIND" in com) differently but (given outside pressures) it will take me time to find the right formulation.  I have no trouble removing the ('_? * 63) parlor trick.

**Comment by alexpantyukhin** [comment]
I think that splitting `VirtualAssistant.command()` is the good idea. It would be much more readeble if to split it for handlers with for example such base class:

```python
class BaseHandler:
	def can_handle(self, command):
		return False

	def handle(self, command):
		return None

```

**Comment by mertyildiran** [comment]
@cclauss I suggest you to replace all `“BLABLA” in com` pattern with a regex ilke [this line](https://github.com/DragonComputer/Dragonfire/blob/master/dragonfire/__init__.py#L383). I think a simple dictionary lookup is not suitable for this task. We should use massive amount of regex or even NLP methods in a single function. If there is another alternative then please let me know. I will be waiting for your right formulation. :blush:

**Comment by mertyildiran** [comment]
Fixed with #55

**Comment by cclauss** [comment]
@alexpantyukhin I like your idea in https://github.com/DragonComputer/Dragonfire/pull/50#issuecomment-341686540 more and more.  It would be possible to create plugin vocabulary where just putting a handler in the right directory would add logic to Dragonfire.  I will explore that.

**Comment by alexpantyukhin** [comment]
@cclauss yeah, It would be interesting to implement. I think I can implement this if @mertyildiran agree with that.

**Comment by cclauss** [comment]
I started on a transatlantic flight last night...  The issues we face are:
1. Sharing state down into so many files
2. Different handler types:
    * exact match
    * in match
    * search and find
    * regex match
    * keyboard commands
3. Priority: which handlers to run first and which last.
    * The exact match handles should run earlier and use a dict for speed
    * I am not a fan of debugging regex so I would keep these to a minimum 

I will submit a DO NOT MERGE pull request please feel free to use as inspiration or ignore and close.

**Pull request closed without merging**
