### PR TITLE
New Features: 'Taking notes' 'Getting Current Time'

### PR DESCRIPTION
**Pull request by MCYBA**
hello mister.

I think there is a useful idea. Taking note, creating ToDo list and reminder features. 
Another one is getting current time jointly hours and minutes.

ı am moving the simple if-else structure for taking note ability to another sub-directory for less complexity

### CODE REVIEW

**Comment by mertyildiran** [comment]
@MCYBA thanks for this magnificent PR! :trophy: As of you stated that you live in Turkey, in https://gitter.im/DragonComputer/Lobby , I also live in Turkey and I'm really looking forward to meet you in person if you would like to. Let's continue our conversation on Gitter. :blush:

**Comment by mertyildiran** [comment]
@MCYBA I have reverted back your changes in `__init__.py` and `README.md` that comes with this PR of yours. https://github.com/DragonComputer/Dragonfire/commit/fc2ad16e7e203d4fb918c9ebfdce76a61f587f3d

Here are the considerations you have to make before sending such PRs:

 - If you are unsure about the formatting of **README.md** then don't include it. Because it's literally the face of the project.
 - Do not give just pseudo examples in **README.md**, give real life examples. If you are unsure about writing a good `README.md` then maybe you should leave it to the maintainer. You can always share your suitable examples via **Conversation** tab in **GitHub PRs**.
 - If you think that the feature you are implementing with the PR is not yet complete then don't send the PR **prematurely**. Send the PR when the feature is **fully implemented**. To avoid duplicate work, declare your intention to implement the feature via [Issues](https://github.com/DragonComputer/Dragonfire/issues) in advance.
 - Make your PRs and commits **atomic**. Don't try to make massive changes and multiple feature additions, or bug fixings all at once. Send them one by one.
 - Make sure that you **don't brake** any well established feature which is implemented by either me(the maintainer) or any other contributor in previous commits.

So you should continue to work on `commands.takenote` and `take_note` modules of yours and when everything is OK, then you can `import` them in `__init__.py` etc.

**Comment by MCYBA** [comment]
@mertyildiran I missed your first commit in this conversation too. I'm so sorry about this. And I was so excited when I become aware of you are living in Turkey. I want to meet you too. And so sorry my delayed response.

I understand what should am I doing. I will be more careful.

**Comment by mertyildiran** [comment]
@MCYBA :blush: I have also added you on LinkedIn. GitHub is not an appropriate platform for casual chatting. We should either use https://gitter.im/DragonComputer/Lobby or some social network like LinkedIn.

**Pull request merged**
